/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _fontFam = 'CustomIcons';

  static const IconData quick_settings = IconData(0xe800, fontFamily: _fontFam);
  static const IconData lock_screen = IconData(0xe801, fontFamily: _fontFam);
  static const IconData fries = IconData(0xe802, fontFamily: _fontFam);
  static const IconData notch = IconData(0xe803, fontFamily: _fontFam);
  static const IconData status_bar = IconData(0xe804, fontFamily: _fontFam);
  static const IconData potatoproject = IconData(0xe805, fontFamily: _fontFam);
}
